//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SharpCrop.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("SharpCrop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add provider.
        /// </summary>
        internal static string ConfigAddProvider {
            get {
                return ResourceManager.GetString("ConfigAddProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider to copy.
        /// </summary>
        internal static string ConfigCopyProvider {
            get {
                return ResourceManager.GetString("ConfigCopyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record in MPEG (ffmpeg required).
        /// </summary>
        internal static string ConfigEnableMpeg {
            get {
                return ResourceManager.GetString("ConfigEnableMpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format.
        /// </summary>
        internal static string ConfigFormat {
            get {
                return ResourceManager.GetString("ConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual scaling.
        /// </summary>
        internal static string ConfigManualScalling {
            get {
                return ResourceManager.GetString("ConfigManualScalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling levels (in percent) for each monitor, separated by whitespaces (e.g. &quot;100 150 90&quot;).
        /// </summary>
        internal static string ConfigManualScallingHelp {
            get {
                return ResourceManager.GetString("ConfigManualScallingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable URL copy.
        /// </summary>
        internal static string ConfigNoCopy {
            get {
                return ResourceManager.GetString("ConfigNoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable image copy.
        /// </summary>
        internal static string ConfigNoImageCopy {
            get {
                return ResourceManager.GetString("ConfigNoImageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable transparency.
        /// </summary>
        internal static string ConfigNoTransparency {
            get {
                return ResourceManager.GetString("ConfigNoTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove provider.
        /// </summary>
        internal static string ConfigRemoveProvider {
            get {
                return ResourceManager.GetString("ConfigRemoveProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load providers on startup.
        /// </summary>
        internal static string ConfigStartupLoad {
            get {
                return ResourceManager.GetString("ConfigStartupLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available!.
        /// </summary>
        internal static string ConfigUpdateLink {
            get {
                return ResourceManager.GetString("ConfigUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video FPS.
        /// </summary>
        internal static string ConfigVideoFps {
            get {
                return ResourceManager.GetString("ConfigVideoFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox.
        /// </summary>
        internal static string Dropbox {
            get {
                return ResourceManager.GetString("Dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding....
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        internal static string FTP {
            get {
                return ResourceManager.GetString("FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive.
        /// </summary>
        internal static string GoogleDrive {
            get {
                return ResourceManager.GetString("GoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local FS.
        /// </summary>
        internal static string LocalFile {
            get {
                return ResourceManager.GetString("LocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        internal static string OneDrive {
            get {
                return ResourceManager.GetString("OneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the &quot;{0}&quot; provider!.
        /// </summary>
        internal static string ProviderRegistrationFailed {
            get {
                return ResourceManager.GetString("ProviderRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered the &quot;{0}&quot; provider!.
        /// </summary>
        internal static string ProviderRegistrationSucceed {
            get {
                return ResourceManager.GetString("ProviderRegistrationSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed using the &quot;{0}&quot; provider!.
        /// </summary>
        internal static string ProviderUploadFailed {
            get {
                return ResourceManager.GetString("ProviderUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to stop!.
        /// </summary>
        internal static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload completed!.
        /// </summary>
        internal static string UploadCompleted {
            get {
                return ResourceManager.GetString("UploadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed! File was saved locally..
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading... ({0}).
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SharpCrop!
        ///
        ///[Esc] Close the crop window
        ///[F1] Open config window
        ///[Left] Image capture
        ///[Right] Video capture.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
