//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpCrop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpCrop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add provider.
        /// </summary>
        internal static string ConfigAddProvider {
            get {
                return ResourceManager.GetString("ConfigAddProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider to copy.
        /// </summary>
        internal static string ConfigCopyProvider {
            get {
                return ResourceManager.GetString("ConfigCopyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record in MPEG (ffmpeg required).
        /// </summary>
        internal static string ConfigEnableMpeg {
            get {
                return ResourceManager.GetString("ConfigEnableMpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format.
        /// </summary>
        internal static string ConfigFormat {
            get {
                return ResourceManager.GetString("ConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual scaling.
        /// </summary>
        internal static string ConfigManualScalling {
            get {
                return ResourceManager.GetString("ConfigManualScalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable URL copy.
        /// </summary>
        internal static string ConfigNoCopy {
            get {
                return ResourceManager.GetString("ConfigNoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch without focus.
        /// </summary>
        internal static string ConfigNoFocus {
            get {
                return ResourceManager.GetString("ConfigNoFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable GIF repeat.
        /// </summary>
        internal static string ConfigNoGifRepeat {
            get {
                return ResourceManager.GetString("ConfigNoGifRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable manual scaling.
        /// </summary>
        internal static string ConfigNoScaling {
            get {
                return ResourceManager.GetString("ConfigNoScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable transparency.
        /// </summary>
        internal static string ConfigNoTransparency {
            get {
                return ResourceManager.GetString("ConfigNoTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove provider.
        /// </summary>
        internal static string ConfigRemoveProvider {
            get {
                return ResourceManager.GetString("ConfigRemoveProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ConfigReset {
            get {
                return ResourceManager.GetString("ConfigReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load providers on startup.
        /// </summary>
        internal static string ConfigStartupLoad {
            get {
                return ResourceManager.GetString("ConfigStartupLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video FPS.
        /// </summary>
        internal static string ConfigVideoFps {
            get {
                return ResourceManager.GetString("ConfigVideoFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding....
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the &quot;{0}&quot; provider!.
        /// </summary>
        internal static string ProviderRegistrationFailed {
            get {
                return ResourceManager.GetString("ProviderRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered the &quot;{0}&quot; provider!.
        /// </summary>
        internal static string ProviderRegistrationSucceed {
            get {
                return ResourceManager.GetString("ProviderRegistrationSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed using the &quot;{0}&quot; provider!.
        /// </summary>
        internal static string ProviderUploadFailed {
            get {
                return ResourceManager.GetString("ProviderUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to stop!.
        /// </summary>
        internal static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload completed!.
        /// </summary>
        internal static string UploadCompleted {
            get {
                return ResourceManager.GetString("UploadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed! File was saved locally..
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading... ({0}).
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SharpCrop!
        ///
        ///[Esc] Close the crop window
        ///[F1] Open config window
        ///[Left] Image capture
        ///[Right] Video capture.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
